# Generated by Django 4.1.3 on 2022-11-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processimages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processedimage",
            options={
                "verbose_name": "1 - ProcessedImage",
                "verbose_name_plural": "1 - ProcessedImages",
            },
        ),
    ]
